name = "beep"
description = "CLI activity sonifier (Ada migration)"
version = "0.1.0-dev"

authors = ["James Tomasino"]
maintainers = ["James Tomasino <james@example.com>"]
maintainers-logins = ["jamestomasino"]

executables = ["beep"]
project-files = ["beep.gpr"]

tags = ["cli", "linux", "audio", "sonifier"]

[[depends-on]]
gnatprove = "*"
