module beepapp

import json
import net
import os
import strconv

pub struct ControlRequest {
pub:
	cmd   string
	key   string
	value string
}

pub struct ControlState {
pub:
	enabled           bool
	profile           string
	master_volume     f32
	ambient_level     f32
	burst_density     f32
	enable_cpu        bool
	enable_system     bool
	enable_network    bool
	debug_fake_input  bool
	log_events        bool
}

pub struct ControlResponse {
pub:
	ok      bool
	message string
	state   ControlState
}

pub struct RuntimeControl {
mut:
	enabled          bool = true
	profile          string
	master_volume    f32 = 1.0
	ambient_level    f32 = 1.0
	burst_density    f32 = 1.0
	enable_cpu       bool = true
	enable_system    bool = true
	enable_network   bool = true
	debug_fake_input bool
	log_events       bool
	quit_requested   bool
}

fn bool_s(v bool) string {
	if v {
		return 'true'
	}
	return 'false'
}

fn format_runtime_config(path string, state ControlState) string {
	mut lines := []string{cap: 16}
	lines << '# beep runtime control snapshot'
	lines << '# generated by save_config'
	lines << 'profile=${state.profile}'
	lines << 'enable_cpu=${bool_s(state.enable_cpu)}'
	lines << 'enable_system=${bool_s(state.enable_system)}'
	lines << 'enable_network=${bool_s(state.enable_network)}'
	lines << 'debug_fake_input=${bool_s(state.debug_fake_input)}'
	lines << 'log_events=${bool_s(state.log_events)}'
	lines << 'master_volume=${state.master_volume:.3f}'
	lines << 'ambient_level=${state.ambient_level:.3f}'
	lines << 'burst_density=${state.burst_density:.3f}'
	lines << ''
	lines << '# saved path: ${path}'
	lines << ''
	return lines.join('\n')
}

fn save_runtime_config(path string, state ControlState) ! {
	dir := os.dir(path)
	if dir != '' {
		os.mkdir_all(dir)!
	}
	os.write_file(path, format_runtime_config(path, state))!
}

fn clamp01(v f32) f32 {
	if v < 0.0 {
		return 0.0
	}
	if v > 1.0 {
		return 1.0
	}
	return v
}

fn parse_bool(v string) ?bool {
	value := v.trim_space().to_lower()
	if value in ['1', 'true', 'yes', 'on'] {
		return true
	}
	if value in ['0', 'false', 'no', 'off'] {
		return false
	}
	return none
}

fn parse_f32(v string) ?f32 {
	n := strconv.atof64(v.trim_space()) or { return none }
	return f32(n)
}

pub fn snapshot(shared rt RuntimeControl) ControlState {
	rlock rt {
		return ControlState{
			enabled:          rt.enabled
			profile:          rt.profile
			master_volume:    rt.master_volume
			ambient_level:    rt.ambient_level
			burst_density:    rt.burst_density
			enable_cpu:       rt.enable_cpu
			enable_system:    rt.enable_system
			enable_network:   rt.enable_network
			debug_fake_input: rt.debug_fake_input
			log_events:       rt.log_events
		}
	}
}

pub fn apply_control(mut req ControlRequest, shared rt RuntimeControl) ControlResponse {
	match req.cmd {
		'get_state' {
			return ControlResponse{true, 'ok', snapshot(shared rt)}
		}
		'quit' {
			lock rt {
				rt.quit_requested = true
			}
			return ControlResponse{true, 'quitting', snapshot(shared rt)}
		}
		'toggle' {
			mut ok := true
			mut msg := 'ok'
			lock rt {
				match req.key {
					'enabled' { rt.enabled = !rt.enabled }
					'enable_cpu' { rt.enable_cpu = !rt.enable_cpu }
					'enable_system' { rt.enable_system = !rt.enable_system }
					'enable_network' { rt.enable_network = !rt.enable_network }
					'log_events' { rt.log_events = !rt.log_events }
					'debug_fake_input' { rt.debug_fake_input = !rt.debug_fake_input }
					else {
						ok = false
						msg = 'unknown toggle key'
					}
				}
			}
			return ControlResponse{ok, msg, snapshot(shared rt)}
		}
		'set' {
			mut ok := true
			mut msg := 'ok'
			lock rt {
				match req.key {
					'profile' {
						rt.profile = req.value
					}
					'master_volume' {
						if x := parse_f32(req.value) {
							rt.master_volume = clamp01(x)
						}
					}
					'ambient_level' {
						if x := parse_f32(req.value) {
							rt.ambient_level = clamp01(x)
						}
					}
					'burst_density' {
						if x := parse_f32(req.value) {
							rt.burst_density = clamp01(x)
						}
					}
					'enabled' {
						if b := parse_bool(req.value) {
							rt.enabled = b
						}
					}
					'enable_cpu' {
						if b := parse_bool(req.value) {
							rt.enable_cpu = b
						}
					}
					'enable_system' {
						if b := parse_bool(req.value) {
							rt.enable_system = b
						}
					}
					'enable_network' {
						if b := parse_bool(req.value) {
							rt.enable_network = b
						}
					}
					'log_events' {
						if b := parse_bool(req.value) {
							rt.log_events = b
						}
					}
					'debug_fake_input' {
						if b := parse_bool(req.value) {
							rt.debug_fake_input = b
						}
					}
					else {
						ok = false
						msg = 'unknown set key'
					}
				}
			}
			return ControlResponse{ok, msg, snapshot(shared rt)}
		}
		else {
			return ControlResponse{false, 'unknown command', snapshot(shared rt)}
		}
	}
}

pub fn run_control_server(addr string, config_path string, shared rt RuntimeControl) ! {
	mut ln := net.listen_tcp(.ip, addr)!
	defer {
		ln.close() or {}
	}
	for {
		mut conn := ln.accept() or { continue }
		spawn handle_control_conn(mut conn, config_path, shared rt)
	}
}

fn handle_control_conn(mut conn net.TcpConn, config_path string, shared rt RuntimeControl) {
	defer {
		conn.close() or {}
	}
	line := conn.read_line()
	if line.len == 0 {
		return
	}
	mut req := json.decode(ControlRequest, line) or {
		resp := ControlResponse{false, 'invalid json request', snapshot(shared rt)}
		conn.write_string(json.encode(resp) + '\n') or {}
		return
	}
	if req.cmd == 'save_config' {
		state := snapshot(shared rt)
		save_runtime_config(config_path, state) or {
			resp := ControlResponse{false, 'failed to save config: ${err}', state}
			conn.write_string(json.encode(resp) + '\n') or {}
			return
		}
		resp := ControlResponse{true, 'saved ${config_path}', state}
		conn.write_string(json.encode(resp) + '\n') or {}
		return
	}
	resp := apply_control(mut req, shared rt)
	conn.write_string(json.encode(resp) + '\n') or {}
}

pub fn send_control(addr string, req ControlRequest) !ControlResponse {
	mut conn := net.dial_tcp(addr)!
	defer {
		conn.close() or {}
	}
	conn.write_string(json.encode(req) + '\n')!
	line := conn.read_line()
	return json.decode(ControlResponse, line)!
}

pub fn default_ipc_addr() string {
	return os.getenv_opt('BEEP_IPC_ADDR') or { '127.0.0.1:48777' }
}
